name: yourworld
description: "Travel tracker"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.273
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  country_icons: ^3.0.0
  google_fonts: ^6.2.1
  flutter_map_cancellable_tile_provider: ^3.1.0
  percent_indicator: ^4.2.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/geo/countries.geo.json

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
